baseURL = "https://www.karlvanheijster.com/"
languageCode = "nl-NL"
title = "dotkarl"
theme = "tale" 
defaultContentLanguage = "nl"
disqusShortname = "notkarlmarx"
ignoreLogs = ['shortcode-x-getremote']
rssLimit = 20
[params]
  commentoEnable = true
  author = "Karl van Heijster"
  css = ["custom.css"]
  description = "Software Ontwikkelen met Karl van Heijster"
[author]
  name = "Karl van Heijster"
[taxonomies]
  tag = "tags"
[menu]
  [[menu.main]]
    identifier = "tags"
    pre = "<svg aria-hidden='true' aria-label='tags'viewBox='0 0 24 24'><path d='M20.59 13.41l-8-8A2 2 0 0 0 10.17 5H5a2 2 0 0 0-2 2v5.17a2 2 0 0 0 .59 1.42l8 8a2 2 0 0 0 2.83 0l6.17-6.17a2 2 0 0 0 0-2.83zM7 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z'/></svg>"
    title = "Tags"
    url = "/tags/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    pre = "<svg aria-hidden='true' aria-label='over mij' viewBox='0 0 24 24'><path d='M12 12c2.7 0 5-2.3 5-5s-2.3-5-5-5-5 2.3-5 5 2.3 5 5 5zm0 2c-3.3 0-10 1.7-10 5v3h20v-3c0-3.3-6.7-5-10-5z'/></svg>"
    title = "Over mij"
    url = "/about/"
    weight = 2
  [[menu.footer]]
    identifier = "about"
    name = "Over mij"
    title = "Over mij"
    url = "/about/"
    weight = 1
  [[menu.footer]]
    identifier = "public-speaking"
    name = "Spreker"
    title = "Spreker"
    url = "/public-speaking/"
    weight = 2
  [[menu.footer]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.footer]]
    identifier = "talks"
    name = "Talks"
    title = "Talks"
    url = "/talks/"
    weight = 4
  [[menu.footer]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true