baseURL = "https://www.karlvanheijster.com/"
languageCode = "nl-NL"
title = "dotkarl"
theme = "tale" 
defaultContentLanguage = "nl"
disqusShortname = "notkarlmarx"
googleAnalytics = "G-BNBE2EVXJS"
rssLimit = 20
[params]
  commentoEnable = true
  author = "Karl van Heijster"
  css = ["custom.css"]
  description = "Software Ontwikkelen met Karl van Heijster"
[author]
  name = "Karl van Heijster"
[taxonomies]
  tag = "tags"
[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Over mij"
    title = "Over mij"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    title = "RSS"
    url = "/index.xml/"
    weight = 3
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true