baseURL = "https://dotkarl.netlify.app/"
languageCode = "nl-NL"
title = "dotkarl"
theme = "tale" 
defaultContentLanguage = "nl"
disqusShortname = "notkarlmarx"
[params]
  commentoEnable = true
  Author = "Karl van Heijster"
[author]
  name = "Karl van Heijster"
[taxonomies]
  tag = "tags"
[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Over mij"
    title = "Over mij"
    url = "/about/"
    weight = 2